### ISSUE TITLE
Search Filter Loading

### ISSUE THREAD

**Issue by CyberPutty** [chingu-voyage7/Bears-Team-15#40]
Search bar needs to not show loading. My suggestion is to return a default search if input <1, or no results if search returns no items.  Instead of auto populating on input we can also have a submit button to avoid redundant queries.

**Comment by artoodeeto** [comment]
@CyberPutty  ok. let me fix this.

**Comment by artoodeeto** [comment]
@CyberPutty heres my PR to fix this issue mike. #45

**Comment by artoodeeto** [comment]
@CyberPutty mike im going to close this.
